//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Saimoe.Models.EF", "ContestantProfile", "Contestant", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Saimoe.Models.EF.Contestant), "Profile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Saimoe.Models.EF.Profile))]

#endregion

namespace Saimoe.Models.EF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SaimoeContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SaimoeContext object using the connection string found in the 'SaimoeContext' section of the application configuration file.
        /// </summary>
        public SaimoeContext() : base("name=SaimoeContext", "SaimoeContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SaimoeContext object.
        /// </summary>
        public SaimoeContext(string connectionString) : base(connectionString, "SaimoeContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SaimoeContext object.
        /// </summary>
        public SaimoeContext(EntityConnection connection) : base(connection, "SaimoeContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contestant> Contestants
        {
            get
            {
                if ((_Contestants == null))
                {
                    _Contestants = base.CreateObjectSet<Contestant>("Contestants");
                }
                return _Contestants;
            }
        }
        private ObjectSet<Contestant> _Contestants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profile> Profiles
        {
            get
            {
                if ((_Profiles == null))
                {
                    _Profiles = base.CreateObjectSet<Profile>("Profiles");
                }
                return _Profiles;
            }
        }
        private ObjectSet<Profile> _Profiles;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contestants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContestants(Contestant contestant)
        {
            base.AddObject("Contestants", contestant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Profiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfiles(Profile profile)
        {
            base.AddObject("Profiles", profile);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Saimoe.Models.EF", Name="Contestant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contestant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contestant object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="googlePlusId">Initial value of the GooglePlusId property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="lastLoginDate">Initial value of the LastLoginDate property.</param>
        public static Contestant CreateContestant(global::System.Int32 id, global::System.String googlePlusId, global::System.DateTime createdDate, global::System.DateTime lastLoginDate)
        {
            Contestant contestant = new Contestant();
            contestant.Id = id;
            contestant.GooglePlusId = googlePlusId;
            contestant.CreatedDate = createdDate;
            contestant.LastLoginDate = lastLoginDate;
            return contestant;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GooglePlusId
        {
            get
            {
                return _GooglePlusId;
            }
            set
            {
                OnGooglePlusIdChanging(value);
                ReportPropertyChanging("GooglePlusId");
                _GooglePlusId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GooglePlusId");
                OnGooglePlusIdChanged();
            }
        }
        private global::System.String _GooglePlusId;
        partial void OnGooglePlusIdChanging(global::System.String value);
        partial void OnGooglePlusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                OnLastLoginDateChanging(value);
                ReportPropertyChanging("LastLoginDate");
                _LastLoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginDate");
                OnLastLoginDateChanged();
            }
        }
        private global::System.DateTime _LastLoginDate;
        partial void OnLastLoginDateChanging(global::System.DateTime value);
        partial void OnLastLoginDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Saimoe.Models.EF", "ContestantProfile", "Profile")]
        public Profile Profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("Saimoe.Models.EF.ContestantProfile", "Profile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("Saimoe.Models.EF.ContestantProfile", "Profile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profile> ProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("Saimoe.Models.EF.ContestantProfile", "Profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profile>("Saimoe.Models.EF.ContestantProfile", "Profile", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Saimoe.Models.EF", Name="Profile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profile object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="interest">Initial value of the Interest property.</param>
        /// <param name="characteristic">Initial value of the Characteristic property.</param>
        /// <param name="actingCute">Initial value of the ActingCute property.</param>
        /// <param name="tagline">Initial value of the Tagline property.</param>
        /// <param name="joinedDate">Initial value of the JoinedDate property.</param>
        public static Profile CreateProfile(global::System.Int32 id, global::System.String interest, global::System.String characteristic, global::System.String actingCute, global::System.String tagline, global::System.DateTime joinedDate)
        {
            Profile profile = new Profile();
            profile.Id = id;
            profile.Interest = interest;
            profile.Characteristic = characteristic;
            profile.ActingCute = actingCute;
            profile.Tagline = tagline;
            profile.JoinedDate = joinedDate;
            return profile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Interest
        {
            get
            {
                return _Interest;
            }
            set
            {
                OnInterestChanging(value);
                ReportPropertyChanging("Interest");
                _Interest = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Interest");
                OnInterestChanged();
            }
        }
        private global::System.String _Interest;
        partial void OnInterestChanging(global::System.String value);
        partial void OnInterestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Characteristic
        {
            get
            {
                return _Characteristic;
            }
            set
            {
                OnCharacteristicChanging(value);
                ReportPropertyChanging("Characteristic");
                _Characteristic = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Characteristic");
                OnCharacteristicChanged();
            }
        }
        private global::System.String _Characteristic;
        partial void OnCharacteristicChanging(global::System.String value);
        partial void OnCharacteristicChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActingCute
        {
            get
            {
                return _ActingCute;
            }
            set
            {
                OnActingCuteChanging(value);
                ReportPropertyChanging("ActingCute");
                _ActingCute = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ActingCute");
                OnActingCuteChanged();
            }
        }
        private global::System.String _ActingCute;
        partial void OnActingCuteChanging(global::System.String value);
        partial void OnActingCuteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegistrationPost
        {
            get
            {
                return _RegistrationPost;
            }
            set
            {
                OnRegistrationPostChanging(value);
                ReportPropertyChanging("RegistrationPost");
                _RegistrationPost = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegistrationPost");
                OnRegistrationPostChanged();
            }
        }
        private global::System.String _RegistrationPost;
        partial void OnRegistrationPostChanging(global::System.String value);
        partial void OnRegistrationPostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tagline
        {
            get
            {
                return _Tagline;
            }
            set
            {
                OnTaglineChanging(value);
                ReportPropertyChanging("Tagline");
                _Tagline = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tagline");
                OnTaglineChanged();
            }
        }
        private global::System.String _Tagline;
        partial void OnTaglineChanging(global::System.String value);
        partial void OnTaglineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime JoinedDate
        {
            get
            {
                return _JoinedDate;
            }
            set
            {
                OnJoinedDateChanging(value);
                ReportPropertyChanging("JoinedDate");
                _JoinedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JoinedDate");
                OnJoinedDateChanged();
            }
        }
        private global::System.DateTime _JoinedDate;
        partial void OnJoinedDateChanging(global::System.DateTime value);
        partial void OnJoinedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Saimoe.Models.EF", "ContestantProfile", "Contestant")]
        public Contestant Contestant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contestant>("Saimoe.Models.EF.ContestantProfile", "Contestant").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contestant>("Saimoe.Models.EF.ContestantProfile", "Contestant").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contestant> ContestantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contestant>("Saimoe.Models.EF.ContestantProfile", "Contestant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contestant>("Saimoe.Models.EF.ContestantProfile", "Contestant", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
