//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saimoe.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saimoe.Resources.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acting cute 的本地化字符串。
        /// </summary>
        public static string ActingCute {
            get {
                return ResourceManager.GetString("ActingCute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Say something cute ~=[,,_,,]:3 的本地化字符串。
        /// </summary>
        public static string ActingCuteDescription {
            get {
                return ResourceManager.GetString("ActingCuteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Characteristic 的本地化字符串。
        /// </summary>
        public static string Characteristic {
            get {
                return ResourceManager.GetString("Characteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;TODO&gt; 的本地化字符串。
        /// </summary>
        public static string CharacteristicDescription {
            get {
                return ResourceManager.GetString("CharacteristicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contestant Profile 的本地化字符串。
        /// </summary>
        public static string ContestantProfile {
            get {
                return ResourceManager.GetString("ContestantProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interest 的本地化字符串。
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 What are you interested in? 的本地化字符串。
        /// </summary>
        public static string InterestDescription {
            get {
                return ResourceManager.GetString("InterestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Join the contest 的本地化字符串。
        /// </summary>
        public static string JoinContest {
            get {
                return ResourceManager.GetString("JoinContest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date of joining 的本地化字符串。
        /// </summary>
        public static string JoiningDate {
            get {
                return ResourceManager.GetString("JoiningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When did you join Google+? 的本地化字符串。
        /// </summary>
        public static string JoiningDateDescription {
            get {
                return ResourceManager.GetString("JoiningDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        public static string JoiningDateMonth {
            get {
                return ResourceManager.GetString("JoiningDateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        public static string JoiningDateYear {
            get {
                return ResourceManager.GetString("JoiningDateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 en 的本地化字符串。
        /// </summary>
        public static string LangCode {
            get {
                return ResourceManager.GetString("LangCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login with Google+ 的本地化字符串。
        /// </summary>
        public static string LoginWithGooglePlus {
            get {
                return ResourceManager.GetString("LoginWithGooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Join 的本地化字符串。
        /// </summary>
        public static string NavRegistration {
            get {
                return ResourceManager.GetString("NavRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Votes 的本地化字符串。
        /// </summary>
        public static string NavVoteList {
            get {
                return ResourceManager.GetString("NavVoteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Results 的本地化字符串。
        /// </summary>
        public static string NavVoteResult {
            get {
                return ResourceManager.GetString("NavVoteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not {0} ? 的本地化字符串。
        /// </summary>
        public static string NotSomebody {
            get {
                return ResourceManager.GetString("NotSomebody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration post 的本地化字符串。
        /// </summary>
        public static string RegistrationPost {
            get {
                return ResourceManager.GetString("RegistrationPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The URL to an additional and external registration post. 的本地化字符串。
        /// </summary>
        public static string RegistrationPostDescription {
            get {
                return ResourceManager.GetString("RegistrationPostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string SiteHome {
            get {
                return ResourceManager.GetString("SiteHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 G+ Moe League 的本地化字符串。
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tagline 的本地化字符串。
        /// </summary>
        public static string Tagline {
            get {
                return ResourceManager.GetString("Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A brief description of you. 的本地化字符串。
        /// </summary>
        public static string TaglineDescription {
            get {
                return ResourceManager.GetString("TaglineDescription", resourceCulture);
            }
        }
    }
}
